# 原マシナリー MV カット表（https://claude.ai/artifact/WybVC5PDPJGPL1YyEDS6hK）の全 41 カット
# refs: refs/ の参照画像, frame: 開始フレームに使う前カット
# 参考動画を流用する予定だった 01・02・08・26・29 も、参考動画が手元にないため生成する
CUTS = [
 dict(no="01", refs=[],
      prompt="Slow push-in from space toward Earth, approaching the Japanese archipelago, soft clouds drifting."),
 dict(no="02", refs=["okazaki"],
      prompt="Aerial descent over the city of Okazaki at dawn, morning mist over the Yahagi River, sunlight touching factory rooftops."),
 dict(no="03", refs=["c1948", "old_shop"],
      prompt="Medium shot. A young craftsman carefully wipes and adjusts an old machine in a small workshop, dust in the slanted window light. Sepia tones."),
 dict(no="04", frame="03",
      prompt="Same composition as the previous shot, now in the present day in full color. An elderly craftsman with swept-back grey hair in a navy work jacket stands in the same spot and gently picks up an old photograph, smiling softly."),
 dict(no="05", refs=["veteran", "factory"],
      prompt="Slow dolly back revealing a bright, spacious modern factory around the elderly craftsman; colleagues working in the background."),
 dict(no="06", refs=[], done=True,
      prompt="(生成済み)"),
 dict(no="07", refs=["operator"],
      prompt="Close-up. A young operator measures a polished metal part with a micrometer, focused eyes, then a macro shot of his fingertips adjusting the dial."),
 dict(no="08", refs=["veteran", "designer"],
      prompt="The elderly craftsman draws a blueprint with a pencil at a wooden drafting table, then rolls it up and hands it to the young woman designer with round glasses, who receives it with both hands and smiles."),
 dict(no="09", refs=["veteran", "designer"],
      prompt="Two-shot at a workbench. The elderly craftsman unrolls an old hand-drawn blueprint; the young designer holds a tablet showing the same part in CAD. They compare and nod to each other."),
 dict(no="10", refs=["factory"],
      prompt="Inside the factory at dawn, the large shutter door rises and golden morning light floods in across the floor, camera slowly pushing forward."),
 dict(no="11", refs=["operator", "factory"],
      prompt="Close-up profile of a young operator pressing buttons on a machine control panel, determined expression, rim light."),
 dict(no="12", refs=["designer", "office"],
      prompt="Over-the-shoulder shot of a young designer working in CAD; lines on the monitor assemble into a 3D machine part."),
 dict(no="13", refs=["factory"],
      prompt="Dramatic low-angle shot slowly tilting up the full height of a huge gantry-type machining center in a bright factory. The machine stands still."),
 dict(no="14", refs=["veteran", "mid", "designer"],
      prompt="A small team gathered around a large blueprint on a table, pointing and laughing together, warm window light."),
 dict(no="15", refs=["mid", "designer", "operator"],
      prompt="Back view of employees walking together toward a wide-open factory door filled with bright light, camera following low."),
 dict(no="16", refs=["factory"],
      prompt="Quiet empty factory at sunset; warm light reflects off the polished metal surfaces of the machines, slow lateral pan."),
 dict(no="17", refs=[],
      prompt="Macro tracking shot along a workbench where a silicon ingot, a clear sapphire block, a glass plate and a milky quartz piece are lined up, glowing in window light."),
 dict(no="18", refs=["mid", "operator"],
      prompt="Close-up of hands assembling a special-purpose machine, tightening bolts with a torque wrench, then a medium shot of two engineers working together."),
 dict(no="19", refs=["designer", "operator"],
      prompt="The young designer and the young operator stand in front of a finished machine, exchange a nod and a small smile."),
 dict(no="20", refs=["designer"],
      prompt="A clean inspection room; a coordinate measuring machine probe touches a metal part while the young designer records the results on a clipboard."),
 dict(no="21", refs=["mid"],
      prompt="A carefully wrapped machine part is loaded onto a truck; the engineer bows politely as the truck departs in the afternoon light."),
 dict(no="22", refs=["veteran", "newbie"],
      prompt="Close-up: an elderly craftsman places his hand over the hand of an eighteen-year-old new recruit in a brand-new uniform, guiding how to hold a precision tool."),
 dict(no="23", refs=["welder", "newbie", "inspector"],
      prompt="A new machine powers on with its indicator lights; employees around it applaud and smile."),
 dict(no="24", refs=["designer", "sales", "mid"],
      prompt="The young designer explains a sketch on a whiteboard to colleagues who nod with interest."),
 dict(no="25", refs=["okazaki"],
      prompt="Wide shot at golden hour overlooking the city of Okazaki from a hill, a factory roof in the foreground."),
 dict(no="26", refs=[],
      prompt="Camera rises from a Japanese city at golden hour up through the clouds into space, pulling back to reveal the whole Earth."),
 dict(no="27", refs=["inspector", "newbie", "sales"],
      prompt="Morning assembly in the factory: employees stand in a row, listening and looking ahead, soft morning light."),
 dict(no="28", refs=["welder", "newbie", "inspector"],
      prompt="Lunch break: employees laughing together while eating bento boxes at a long table, relaxed and warm."),
 dict(no="29", refs=["designer", "office"],
      prompt="The young designer by the office window turns toward the camera and smiles warmly, sunlight on her face."),
 dict(no="30", refs=["factory"],
      prompt="Exterior of the factory at dusk, windows lighting up one by one, sky turning from orange to blue."),
 dict(no="31", refs=["c1948", "old_shop"],
      prompt="Sepia-toned close-up: a young craftsman's hands turn the handle of an old machine in a 1940s workshop."),
 dict(no="32", frame="31",
      prompt="Same composition in full color, present day: a young operator's hands in a navy work uniform operate the control panel of a modern machine."),
 dict(no="33", refs=["veteran", "designer"],
      prompt="A pencil-drawn blueprint slowly dissolves into the same design on a CAD screen, two hands, old and young, resting side by side."),
 dict(no="34", refs=["factory"],
      prompt="A massive machined steel part is slowly lifted by an overhead crane, workers guiding it, camera tilting up with it."),
 dict(no="35", refs=["veteran", "inspector", "newbie"],
      prompt="All employees gathered in front of the factory, smiling; the camera pulls back and rises to reveal the whole group."),
 dict(no="36", refs=["veteran", "designer"],
      prompt="The elderly craftsman and the young designer stand side by side looking up at a finished machine, light on their faces."),
 dict(no="37", refs=["factory"],
      prompt="Rising aerial shot of the factory at sunrise, long shadows, birds crossing the sky."),
 dict(no="38", refs=["welder", "sales", "newbie"],
      prompt="Employees look up toward bright light with determined smiles, wind moving their hair, camera slowly pushing in."),
 dict(no="39", refs=["factory"],
      prompt="Quiet factory exterior at dusk, warm and peaceful, gentle breeze."),
 dict(no="40", refs=[],
      prompt="Still-life on a wooden workbench: an old vernier caliper next to a modern digital measuring instrument, soft evening window light."),
 dict(no="41", refs=["okazaki"],
      prompt="Wide evening sky with soft clouds over Okazaki, calm and spacious."),
 # 曲に合わせて足したカット（カット表の時刻より実際の曲が長く歌う部分を埋める）
 dict(no="42", refs=["veteran", "factory"],
      prompt="Close-up: the elderly craftsman slowly runs his fingertip along a freshly machined, mirror-smooth metal surface, checking it against the light with a straightedge, utterly focused."),
 dict(no="43", refs=["mid", "welder", "factory"],
      prompt="A cover cloth is pulled off a newly finished special-purpose machine in the factory; the engineers look at it proudly."),
 dict(no="44", refs=["factory"],
      prompt="Exterior of a modern Japanese factory building in bright daylight, blue sky, camera slowly rising up the facade."),
 dict(no="45", refs=["sales", "mid", "factory"],
      prompt="In the factory, the salesman in a suit and the engineer show a finished machine to a visiting client in a suit; the client nods, impressed, and they shake hands."),
 dict(no="46", refs=["okazaki"],
      prompt="Night view: the camera rises from a lit-up factory to reveal the glowing city lights of Okazaki and the river under a starry sky."),
 dict(no="47", refs=[],
      prompt="Close-up of an old photo album on a wooden desk; a gentle breeze turns the pages of faded sepia photographs of a small 1940s machine workshop and its workers."),
 dict(no="48", refs=["factory"],
      prompt="Time-lapse of a bright factory from morning to evening: sunlight beams sweep across the floor, machines running, workers passing by as soft blurs."),
 dict(no="49", refs=[],
      prompt="Twilight sky slowly deepening from orange to deep blue, soft clouds drifting, the first stars appearing. Calm and spacious."),
]

# 実際の曲（song.mp3、4:35.8）に合わせたカット割り: (カット番号, 開始秒, 終了秒)
# 歌の時刻は Gemini で曲を書き起こして測った（song_transcript.json）
TIMELINE = [
 ("01", 0.0, 1.8), ("03", 1.8, 7.4), ("04", 7.4, 14.3), ("05", 14.3, 20.9), ("02", 20.9, 27.4), ("16", 27.4, 32.4),
 ("06", 32.4, 39.4), ("07", 39.4, 47.7), ("42", 47.7, 52.4), ("08", 52.4, 60.0),
 ("09", 60.0, 66.4), ("10", 66.4, 73.6),
 ("11", 73.6, 75.3), ("12", 75.3, 77.0), ("13", 77.0, 78.6), ("14", 78.6, 86.3), ("43", 86.3, 90.0),
 ("15", 90.0, 96.4), ("44", 96.4, 100.4),
 ("17", 100.4, 107.3), ("18", 107.3, 114.0), ("19", 114.0, 119.8), ("45", 119.8, 126.7),
 ("20", 126.7, 133.7), ("21", 133.7, 141.4),
 ("22", 141.4, 148.7), ("23", 148.7, 154.5), ("24", 154.5, 158.2), ("25", 158.2, 161.2), ("26", 161.2, 168.8),
 ("27", 168.8, 175.7), ("28", 175.7, 178.8), ("29", 178.8, 183.9), ("30", 183.9, 189.9), ("46", 189.9, 195.9),
 ("47", 195.9, 202.9), ("48", 202.9, 209.8),
 ("31", 209.8, 213.3), ("32", 213.3, 216.9), ("33", 216.9, 222.8), ("34", 222.8, 226.7), ("35", 226.7, 233.3),
 ("36", 233.3, 236.8), ("37", 236.8, 241.3), ("38", 241.3, 247.4),
 ("39", 247.4, 253.9), ("40", 253.9, 258.9), ("41", 258.9, 266.9), ("49", 266.9, 275.8),
]

# 歌詞テロップ: (開始秒, 終了秒, 文字)
LYRICS = [
 (1.8, 4.6, "1948年"), (4.6, 7.4, "ここから始まった"), (7.4, 10.5, "受け継いだ技術"), (10.5, 14.3, "積み重ねた想い"),
 (14.3, 17.6, "時代が変わっても"), (17.6, 20.9, "変わらないものがある"), (20.9, 27.4, "ものづくりへの　情熱"),
 (32.4, 36.0, "鉄を削り　形を生み出す"), (36.0, 39.4, "大きな素材に　挑み続ける"), (39.4, 44.8, "一ミリ　一ミクロン"),
 (44.8, 47.7, "その先にある精度を追い"), (47.7, 52.4, "見えないところまで　妥協せず向き合う"),
 (52.4, 55.8, "技術は　人から人へ"), (55.8, 60.0, "想いは　未来へ"),
 (60.0, 63.0, "守るべき技術は　守り抜く"), (63.0, 66.4, "変えるべきものは　変えていく"),
 (66.4, 68.0, "昨日を超えて"), (68.0, 69.6, "今日を超えて"), (69.6, 73.6, "まだ見ぬ未来へ"),
 (73.6, 75.3, "技術力"), (75.3, 77.0, "設計力"), (77.0, 78.6, "設備力"), (78.6, 80.3, "人間力"),
 (80.3, 86.3, "すべての力を　ひとつにして"), (86.3, 90.0, "まだない価値を　創り出せ"),
 (90.0, 91.5, "この手で"), (91.5, 92.9, "この技術で"), (92.9, 96.4, "未来を　切り拓け"), (96.4, 100.4, "原マシナリー"),
 (100.4, 103.7, "難しい素材も　不可能じゃない"), (103.7, 107.3, "シリコン　サファイア　ガラス　石英"),
 (107.3, 110.8, "削る　磨く　組み上げる"), (110.8, 114.0, "一つひとつに　技術が宿る"),
 (114.0, 116.7, "設計から　加工まで"), (116.7, 119.8, "一貫して　応えていく"), (119.8, 126.7, "求められるものの　その先へ"),
 (126.7, 128.9, "品質を追い"), (128.9, 131.0, "コストに挑み"), (131.0, 133.7, "納期を守る"),
 (133.7, 135.5, "信頼は"), (135.5, 138.4, "一つひとつの仕事から"), (138.4, 141.4, "積み上げていく"),
 (141.4, 144.9, "技術力　設計力"), (144.9, 148.7, "設備力　人間力"), (148.7, 154.5, "受け継いだ力を　進化させ"),
 (154.5, 158.2, "次の時代を　創り出せ"), (158.2, 159.8, "この街から"), (159.8, 161.2, "世界へ"),
 (161.2, 164.4, "未来を　動かせ"), (164.4, 168.8, "原マシナリー"),
 (168.8, 172.5, "変化を恐れない"), (172.5, 175.7, "挑戦を止めない"), (175.7, 177.3, "人がいる"), (177.3, 178.8, "技術がある"),
 (178.8, 181.5, "仲間がいる"), (181.5, 183.9, "だから　できる"),
 (183.9, 186.9, "一つの会社から"), (186.9, 189.9, "一つの技術から"), (189.9, 195.9, "世界の未来へ"),
 (209.8, 213.3, "技術力　設計力"), (213.3, 216.9, "設備力　人間力"), (216.9, 222.8, "四つの力を　ひとつにして"),
 (222.8, 226.7, "新しい時代を　切り拓け"), (226.7, 230.1, "1948年から"), (230.1, 233.3, "受け継いだ　ものづくり"),
 (233.3, 235.2, "100年企業へ"), (235.2, 236.8, "その先へ"), (236.8, 239.2, "まだ見ぬ未来を"), (239.2, 241.3, "この手で創る"),
 (241.3, 242.7, "技術で"), (242.7, 244.2, "未来を"), (244.2, 245.8, "切り拓け"), (245.8, 247.4, "原マシナリー！"),
 (247.4, 250.7, "受け継ぐ技術"), (250.7, 253.9, "挑み続ける心"), (253.9, 258.9, "ものづくりの未来へ"),
]

# 左上の年号・地名: (開始秒, 終了秒, 文字)
TAGS = [(2.1, 7.1, "1948"), (7.7, 14.0, "2026"), (21.2, 27.1, "岡崎"), (158.4, 161.0, "岡崎"), (210.1, 213.0, "1948"),
        (213.6, 216.6, "2026"), (233.6, 236.5, "2048")]

# 最後の社名（ロゴの代わり）の表示開始秒
LOGO_AT = 259.5

# 社員の皆さんで作り直すカット（架空の人物から差し替え）。ここにある番号は CUTS の同じ番号を上書きする
RECAST = {
 "04": (["part_okami", "factory"], "In the bright present-day factory, the late founder's elderly wife with soft brown hair gently picks up an old sepia photograph of the 1948 workshop and smiles softly."),
 "05": (["adv_all", "factory"], "Slow dolly back from the dignified senior advisor in his seventies, revealing a bright, spacious modern factory around him; colleagues working in the background."),
 "07": (["machinist", "factory"], "Close-up. The slim master machinist with glasses measures a polished metal part with a micrometer, focused eyes, then a macro shot of his fingertips adjusting the dial."),
 "08": (["adv_slim", "des_smile"], "The slim elderly advisor draws a machine design with a pencil at a wooden drafting table, then hands the rolled drawing to the smiling designer with glasses, who receives it with both hands."),
 "09": (["des_white", "des_smile"], "Two-shot at a workbench. The white-haired senior designer unrolls an old hand-drawn blueprint; the smiling designer with glasses holds a tablet showing the same part in CAD. They compare and nod."),
 "11": (["machinist", "factory"], "Close-up profile of the slim master machinist with glasses pressing buttons on a machine control panel, determined expression, rim light."),
 "12": (["des_smile", "office"], "Over-the-shoulder shot of the smiling designer with glasses working in CAD; lines on the monitor assemble into a 3D machine part."),
 "14": (["des_white", "assembler", "new_glasses"], "A small team gathered around a large blueprint on a table, pointing and laughing together, warm window light."),
 "15": (["president", "vp", "new_viet"], "Back view of employees walking together toward a wide-open factory door filled with bright light, camera following low."),
 "18": (["assembler", "new_pony_m"], "Close-up of hands assembling a special-purpose machine, tightening bolts with a torque wrench, then a medium shot of the bearded master assembler teaching the new recruit with a ponytail."),
 "19": (["des_smile", "assembler"], "The smiling designer with glasses and the bearded master assembler stand in front of a finished machine, exchange a nod and a small smile."),
 "20": (["insp_woman", "qc_chief"], "A clean inspection room; a coordinate measuring machine probe touches a metal part while the short-haired inspector records results and the quality chief checks over her shoulder."),
 "21": (["president", "vp"], "A carefully wrapped machine part is loaded onto a truck; the company president and the petite vice president bow politely as the truck departs in the afternoon light."),
 "22": (["adv_big", "new_shy"], "Close-up: the elderly machining advisor places his weathered hand over the hand of a shy young recruit, guiding how to hold a precision tool."),
 "23": (["assembler", "new_viet", "part_pony"], "A new machine powers on with its indicator lights; employees around it applaud and smile, the Vietnamese recruit cheering happily."),
 "24": (["des_white", "new_glasses", "new_shy"], "The white-haired senior designer explains a sketch on a whiteboard to two new recruits who nod with interest."),
 "27": (["president", "vp", "clerk"], "Morning assembly in the factory: the president speaks to the employees standing in a row, the vice president beside him, everyone listening, soft morning light."),
 "28": (["new_viet", "part_okami", "part_pony"], "Lunch break: employees laughing together while eating bento boxes at a long table; the talkative Vietnamese recruit tells a story, relaxed and warm."),
 "29": (["vp", "office"], "The petite vice president by the office window turns toward the camera and smiles warmly, sunlight on her face."),
 "32": (["machinist", "factory"], "Close-up in full color, present day: the master machinist's hands operate the control panel of a modern machine."),
 "33": (["adv_slim", "new_shy"], "A pencil-drawn blueprint slowly dissolves into the same design on a CAD screen; an old hand and a young hand rest side by side on the desk."),
 "34": (["adv_big", "new_pony_m", "factory"], "A massive machined steel part is slowly lifted by an overhead crane, the elderly advisor and a worker guiding it, camera tilting up with it."),
 "35": (["president", "vp", "adv_all"], "All twenty-one employees of a small company gathered in front of the factory, smiling, the president and vice president in the center; the camera pulls back and rises to reveal the whole group."),
 "36": (["adv_all", "new_shy"], "The elderly senior advisor and the shy young recruit stand side by side looking up at a finished machine, light on their faces."),
 "38": (["new_viet", "insp_woman", "clerk"], "Employees look up toward bright light with determined smiles, wind moving their hair, camera slowly pushing in."),
 "42": (["adv_big", "factory"], "Close-up: the elderly machining advisor slowly runs his fingertip along a freshly machined, mirror-smooth metal surface, checking it against the light with a straightedge, utterly focused."),
 "43": (["assembler", "des_smile", "factory"], "A cover cloth is pulled off a newly finished special-purpose machine in the factory; the bearded assembler and the designer look at it proudly."),
 "45": (["president", "des_white", "factory"], "In the factory, the president and the white-haired designer show a finished machine to a visiting client in a suit; the client nods, impressed, and they shake hands."),
}
for _c in CUTS:
    if _c["no"] in RECAST:
        _c["refs"], _c["prompt"] = RECAST[_c["no"]]
        _c.pop("frame", None)
