# 原マシナリー MV カット表（https://claude.ai/artifact/WybVC5PDPJGPL1YyEDS6hK）の全 41 カット
# start: 曲の中での開始秒, dur: 使う長さ（秒）, refs: refs/ の参照画像, frame: 開始フレームに使う前カット
# 参考動画を流用する予定だった 01・02・08・26・29 も、参考動画が手元にないため生成する
CUTS = [
 dict(no="01", start=0.0, dur=4.5, lyric="", tc="", refs=[],
      prompt="Slow push-in from space toward Earth, approaching the Japanese archipelago, soft clouds drifting."),
 dict(no="02", start=4.5, dur=4.5, lyric="", tc="岡崎", refs=["okazaki"],
      prompt="Aerial descent over the city of Okazaki at dawn, morning mist over the Yahagi River, sunlight touching factory rooftops."),
 dict(no="03", start=9.0, dur=7.4, lyric="1948年　ここから始まった", tc="1948", refs=["c1948", "old_shop"],
      prompt="Medium shot. A young craftsman carefully wipes and adjusts an old machine in a small workshop, dust in the slanted window light. Sepia tones."),
 dict(no="04", start=16.4, dur=7.4, lyric="受け継いだ技術　積み重ねた想い／時代が変わっても", tc="2026", frame="03",
      prompt="Same composition as the previous shot, now in the present day in full color. An elderly craftsman with swept-back grey hair in a navy work jacket stands in the same spot and gently picks up an old photograph, smiling softly."),
 dict(no="05", start=23.8, dur=7.4, lyric="変わらないものがある／ものづくりへの　情熱", tc="", refs=["veteran", "factory"],
      prompt="Slow dolly back revealing a bright, spacious modern factory around the elderly craftsman; colleagues working in the background."),
 dict(no="06", start=31.2, dur=7.5, lyric="鉄を削り　形を生み出す／大きな素材に　挑み続ける", tc="", refs=[], done=True,
      prompt="(生成済み)"),
 dict(no="07", start=38.7, dur=7.5, lyric="一ミリ　一ミクロン／その先にある精度を追い", tc="", refs=["operator"],
      prompt="Close-up. A young operator measures a polished metal part with a micrometer, focused eyes, then a macro shot of his fingertips adjusting the dial."),
 dict(no="08", start=46.2, dur=7.5, lyric="技術は　人から人へ／想いは　未来へ", tc="", refs=["veteran", "designer"],
      prompt="The elderly craftsman draws a blueprint with a pencil at a wooden drafting table, then rolls it up and hands it to the young woman designer with round glasses, who receives it with both hands and smiles."),
 dict(no="09", start=53.7, dur=7.6, lyric="守るべき技術は　守り抜く／変えるべきものは　変えていく", tc="", refs=["veteran", "designer"],
      prompt="Two-shot at a workbench. The elderly craftsman unrolls an old hand-drawn blueprint; the young designer holds a tablet showing the same part in CAD. They compare and nod to each other."),
 dict(no="10", start=61.3, dur=7.6, lyric="昨日を超えて／今日を超えて／まだ見ぬ未来へ", tc="", refs=["factory"],
      prompt="Inside the factory at dawn, the large shutter door rises and golden morning light floods in across the floor, camera slowly pushing forward."),
 dict(no="11", start=68.9, dur=5.8, lyric="技術力", tc="", refs=["operator", "factory"],
      prompt="Close-up profile of a young operator pressing buttons on a machine control panel, determined expression, rim light."),
 dict(no="12", start=74.7, dur=5.8, lyric="設計力", tc="", refs=["designer", "office"],
      prompt="Over-the-shoulder shot of a young designer working in CAD; lines on the monitor assemble into a 3D machine part."),
 dict(no="13", start=80.5, dur=5.8, lyric="設備力", tc="", refs=["factory"],
      prompt="Dramatic low-angle shot slowly tilting up the full height of a huge gantry-type machining center in a bright factory. The machine stands still."),
 dict(no="14", start=86.3, dur=5.8, lyric="人間力／すべての力を　ひとつにして／まだない価値を　創り出せ", tc="", refs=["veteran", "mid", "designer"],
      prompt="A small team gathered around a large blueprint on a table, pointing and laughing together, warm window light."),
 dict(no="15", start=92.1, dur=5.8, lyric="この手で／この技術で／未来を　切り拓け／原マシナリー", tc="", refs=["mid", "designer", "operator"],
      prompt="Back view of employees walking together toward a wide-open factory door filled with bright light, camera following low."),
 dict(no="16", start=97.9, dur=6.8, lyric="", tc="", refs=["factory"],
      prompt="Quiet empty factory at sunset; warm light reflects off the polished metal surfaces of the machines, slow lateral pan."),
 dict(no="17", start=104.7, dur=5.7, lyric="難しい素材も　不可能じゃない／シリコン　サファイア　ガラス　石英", tc="", refs=[],
      prompt="Macro tracking shot along a workbench where a silicon ingot, a clear sapphire block, a glass plate and a milky quartz piece are lined up, glowing in window light."),
 dict(no="18", start=110.4, dur=5.7, lyric="削る　磨く　組み上げる／一つひとつに　技術が宿る", tc="", refs=["mid", "operator"],
      prompt="Close-up of hands assembling a special-purpose machine, tightening bolts with a torque wrench, then a medium shot of two engineers working together."),
 dict(no="19", start=116.1, dur=5.7, lyric="設計から　加工まで／一貫して　応えていく", tc="", refs=["designer", "operator"],
      prompt="The young designer and the young operator stand in front of a finished machine, exchange a nod and a small smile."),
 dict(no="20", start=121.8, dur=7.5, lyric="品質を追い／コストに挑み／納期を守る", tc="", refs=["designer"],
      prompt="A clean inspection room; a coordinate measuring machine probe touches a metal part while the young designer records the results on a clipboard."),
 dict(no="21", start=129.3, dur=7.5, lyric="信頼は／一つひとつの仕事から／積み上げていく", tc="", refs=["mid"],
      prompt="A carefully wrapped machine part is loaded onto a truck; the engineer bows politely as the truck departs in the afternoon light."),
 dict(no="22", start=136.8, dur=5.8, lyric="技術力　設計力", tc="", refs=["veteran", "operator"],
      prompt="Close-up: an elderly craftsman places his hand over a young operator's hand, guiding how to hold a precision tool."),
 dict(no="23", start=142.6, dur=5.8, lyric="設備力　人間力／受け継いだ力を　進化させ", tc="", refs=["mid", "designer", "operator"],
      prompt="A new machine powers on with its indicator lights; employees around it applaud and smile."),
 dict(no="24", start=148.4, dur=5.8, lyric="次の時代を　創り出せ", tc="", refs=["designer", "mid", "office"],
      prompt="The young designer explains a sketch on a whiteboard to colleagues who nod with interest."),
 dict(no="25", start=154.2, dur=5.8, lyric="この街から", tc="岡崎", refs=["okazaki"],
      prompt="Wide shot at golden hour overlooking the city of Okazaki from a hill, a factory roof in the foreground."),
 dict(no="26", start=160.0, dur=5.8, lyric="世界へ／未来を　動かせ／原マシナリー", tc="", refs=[],
      prompt="Camera rises from a Japanese city at golden hour up through the clouds into space, pulling back to reveal the whole Earth."),
 dict(no="27", start=165.8, dur=7.7, lyric="変化を恐れない／挑戦を止めない／人がいる", tc="", refs=["veteran", "mid", "designer"],
      prompt="Morning assembly in the factory: employees stand in a row, listening and looking ahead, soft morning light."),
 dict(no="28", start=173.5, dur=7.7, lyric="技術がある／仲間がいる", tc="", refs=["mid", "designer", "operator"],
      prompt="Lunch break: employees laughing together while eating bento boxes at a long table, relaxed and warm."),
 dict(no="29", start=181.2, dur=7.7, lyric="だから　できる", tc="", refs=["designer", "office"],
      prompt="The young designer by the office window turns toward the camera and smiles warmly, sunlight on her face."),
 dict(no="30", start=188.9, dur=7.7, lyric="一つの会社から／一つの技術から／世界の未来へ", tc="", refs=["factory"],
      prompt="Exterior of the factory at dusk, windows lighting up one by one, sky turning from orange to blue."),
 dict(no="31", start=196.6, dur=7.3, lyric="技術力　設計力", tc="1948", refs=["c1948", "old_shop"],
      prompt="Sepia-toned close-up: a young craftsman's hands turn the handle of an old machine in a 1940s workshop."),
 dict(no="32", start=203.9, dur=7.3, lyric="設備力　人間力", tc="2026", frame="31",
      prompt="Same composition in full color, present day: a young operator's hands in a navy work uniform operate the control panel of a modern machine."),
 dict(no="33", start=211.2, dur=7.3, lyric="四つの力を　ひとつにして", tc="", refs=["veteran", "designer"],
      prompt="A pencil-drawn blueprint slowly dissolves into the same design on a CAD screen, two hands, old and young, resting side by side."),
 dict(no="34", start=218.5, dur=7.3, lyric="新しい時代を　切り拓け", tc="", refs=["factory"],
      prompt="A massive machined steel part is slowly lifted by an overhead crane, workers guiding it, camera tilting up with it."),
 dict(no="35", start=225.8, dur=7.3, lyric="1948年から／受け継いだ　ものづくり", tc="", refs=["veteran", "designer", "operator"],
      prompt="All employees gathered in front of the factory, smiling; the camera pulls back and rises to reveal the whole group."),
 dict(no="36", start=233.1, dur=7.3, lyric="100年企業へ／その先へ", tc="2048", refs=["veteran", "designer"],
      prompt="The elderly craftsman and the young designer stand side by side looking up at a finished machine, light on their faces."),
 dict(no="37", start=240.4, dur=7.3, lyric="まだ見ぬ未来を／この手で創る", tc="", refs=["factory"],
      prompt="Rising aerial shot of the factory at sunrise, long shadows, birds crossing the sky."),
 dict(no="38", start=247.7, dur=7.3, lyric="技術で／未来を／切り拓け／原マシナリー！", tc="", refs=["mid", "designer", "operator"],
      prompt="Employees look up toward bright light with determined smiles, wind moving their hair, camera slowly pushing in."),
 dict(no="39", start=255.0, dur=6.9, lyric="受け継ぐ技術", tc="", refs=["factory"],
      prompt="Quiet factory exterior at dusk, warm and peaceful, gentle breeze."),
 dict(no="40", start=261.9, dur=6.9, lyric="挑み続ける心／ものづくりの未来へ", tc="", refs=[],
      prompt="Still-life on a wooden workbench: an old vernier caliper next to a modern digital measuring instrument, soft evening window light."),
 dict(no="41", start=268.8, dur=7.2, lyric="", tc="原マシナリー", refs=["okazaki"],
      prompt="Wide evening sky with soft clouds over Okazaki, calm and spacious."),
]
