# 原マシナリーを支える社員（ユーザーから聞いた実際の顔ぶれをもとにした、アニメ調の人物設定）
# key: (日本語の説明, 英語の見た目)
# 服装: 全員同じ紺の会社の作業着で統一
# 髪: 顧問 3 人と白髪の設計者以外の男性は黒髪、女性は暗めの茶髪
STAFF = {
 "part_pony":   ("パート（掃除・雑務）50代女性、ポニーテール", "a beautiful Japanese woman in her fifties with dark brown hair in a neat ponytail, gentle smile, youthful and lively, looks about ten years younger than her age, smooth skin, bright eyes, wearing the company's standard uniform (navy blue work jacket with a small white emblem on the chest and matching navy work trousers, same as all other employees)"),
 "part_okami":  ("パート・先代社長の奥さん 70代女性、暗めの茶髪", "a warm Japanese woman in her seventies with soft dark brown hair (no grey at all), the late founder's wife who watches over everyone, youthful and lively, looks about ten years younger than her age, smooth skin, bright eyes, wearing the company's standard uniform (navy blue work jacket with a small white emblem on the chest and matching navy work trousers, same as all other employees)"),
 "new_shy":     ("新人（大物金属加工） 20代男性、少し内気", "a slightly shy young Japanese man in his twenties with short black hair, modest reserved expression, wearing the company's standard uniform (navy blue work jacket with a small white emblem on the chest and matching navy work trousers, same as all other employees)"),
 "new_viet":    ("新人（大物金属加工） 35歳くらいのベトナム人男性、おしゃべりで一生懸命", "a cheerful Vietnamese man around thirty-five with short black hair and a big friendly grin, talkative and hardworking, wearing the company's standard uniform (navy blue work jacket with a small white emblem on the chest and matching navy work trousers, same as all other employees)"),
 "new_pony_m":  ("新人（大物金属加工） 50代男性、ポニーテール、気さく", "a friendly easygoing Japanese man in his fifties with long jet-black hair (no grey at all) tied in a ponytail, no apron, wearing the company's standard uniform (navy blue work jacket with a small white emblem on the chest and matching navy work trousers, same as all other employees)"),
 "new_glasses": ("新人（大物金属加工の完成品検査）55歳くらいの男性、メガネ、物知り", "a knowledgeable Japanese man around fifty-five with glasses and neatly combed black hair, thoughtful look, inspects finished large machined parts, wearing the company's standard uniform (navy blue work jacket with a small white emblem on the chest and matching navy work trousers, same as all other employees)"),
 "machinist":   ("金属加工の熟練工 50代男性、眼鏡・短髪・細身", "a slim Japanese master machinist in his fifties with short black hair and glasses, calm focused eyes, wearing the company's standard uniform (navy blue work jacket with a small white emblem on the chest and matching navy work trousers, same as all other employees)"),
 "assembler":   ("装置組付けの熟練工 50代男性、眼鏡・髭・大柄", "a sturdy, slightly large Japanese master assembler in his fifties with short black hair, glasses and a short black beard, reliable presence, wearing the company's standard uniform (navy blue work jacket with a small white emblem on the chest and matching navy work trousers, same as all other employees)"),
 "clerk":       ("総務・経理 30代男性、あたふたしつつ真面目", "an earnest Japanese office clerk in his thirties with neat short black hair, slightly flustered but diligent, wearing the company's standard uniform (navy blue work jacket with a small white emblem on the chest and matching navy work trousers, same as all other employees)"),
 "insp_woman":  ("検査 40歳くらいの女性、ショートカット、おっとり", "a gentle, calm Japanese woman around forty with short dark brown hair, responsible and kind, youthful and lively, looks about ten years younger than her age, smooth skin, bright eyes, wearing the company's standard uniform (navy blue work jacket with a small white emblem on the chest and matching navy work trousers, same as all other employees)"),
 "qc_chief":    ("品質課 課長 60代", "a Japanese quality control section chief in his sixties with short black hair, strict and dependable, wearing the company's standard uniform (navy blue work jacket with a small white emblem on the chest and matching navy work trousers, same as all other employees)"),
 "insp_mid":    ("検査 60代、皆の話を聞いて仕事を回す", "an approachable Japanese man in his sixties with jet-black hair (no grey at all) and a kind face, a good listener, wearing the company's standard uniform (navy blue work jacket with a small white emblem on the chest and matching navy work trousers, same as all other employees)"),
 "des_smile":   ("装置設計 50代男性、細身・眼鏡・いつも笑顔", "a slim Japanese machine designer in his fifties with black hair and glasses and a constant warm smile, wearing the company's standard uniform (navy blue work jacket with a small white emblem on the chest and matching navy work trousers, same as all other employees)"),
 "des_white":   ("装置設計 60代男性、白髪で若々しい", "a vigorous Japanese machine designer in his sixties with white hair, sharp energetic eyes, wearing the company's standard uniform (navy blue work jacket with a small white emblem on the chest and matching navy work trousers, same as all other employees)"),
 "adv_all":     ("顧問 70代男性、全部門の相談役（元・装置部門）", "a dignified Japanese man in his seventies, senior advisor to all departments, grey hair, wise gentle eyes, wearing the company's standard uniform (navy blue work jacket with a small white emblem on the chest and matching navy work trousers, same as all other employees)"),
 "adv_big":     ("顧問 70代男性、大物金属加工の相談役", "a strong-looking Japanese man in his seventies, advisor for large-part machining, short white hair, weathered hands, wearing the company's standard uniform (navy blue work jacket with a small white emblem on the chest and matching navy work trousers, same as all other employees)"),
 "adv_slim":    ("顧問 70代男性、細身、装置の構想・技術の相談役", "a slim, intellectual Japanese man in his seventies, advisor on machine design concepts, thin white hair, wearing the company's standard uniform (navy blue work jacket with a small white emblem on the chest and matching navy work trousers, same as all other employees)"),
 "driver":      ("製品を 3t トラックで運ぶ 70代男性、小柄・丁寧・笑顔", "a small, polite Japanese truck driver in his seventies with a wonderful warm smile, short jet-black hair (no grey at all), careful and courteous, wearing the company's standard uniform (navy blue work jacket with a small white emblem on the chest and matching navy work trousers, same as all other employees)"),
 "concept":     ("装置の構想担当 70代男性、少しふくよか・元気で知的・笑顔", "a cheerful, slightly plump Japanese man in his seventies who conceives machine concepts, clean-shaven, jet-black hair (no grey at all), bright intelligent eyes, always smiling, energetic, wearing the company's standard uniform (navy blue work jacket with a small white emblem on the chest and matching navy work trousers, same as all other employees)"),
 "president":   ("社長 40歳くらいの男性", "a Japanese company president around forty with neat short black hair, determined and warm, wearing the company's standard uniform (navy blue work jacket with a small white emblem on the chest and matching navy work trousers, same as all other employees)"),
 "vp":          ("副社長 50代の小柄な女性、おっとりしつつキリッと", "a petite Japanese woman in her fifties, the vice president, neat short dark brown hair, gentle yet sharp and dignified, motherly, youthful and lively, looks about ten years younger than her age, smooth skin, bright eyes, wearing the company's standard uniform (navy blue work jacket with a small white emblem on the chest and matching navy work trousers, same as all other employees)"),
}
